### ISSUE TITLE
confusing error messages 

### ISSUE THREAD

**Issue by aloifolia** [reasonml-community/error-message-improvement#13]
I am currently learning ReasonML. Therefore, I have to try a lot when something is not thoroughly explained in the docs (or when I do not find such explanations). I tinkered a bit with objects and came across error messages which were not quite plausible to me.

code:
```
  type foo = {. age: int, name: string };
  let data: foo = {
    pub age = 1;
    pri name = "sdf";
  }
```
error message:
```
  This is:
    {. age : int }
  But somewhere wanted:
    foo
  The first object type has no method name
```
What I think could be improved:
1. "somewhere" is confusing since we know that it is data who wants to be of type `foo`. 
2. "name" is not a method as far as I can see
3. Does "first object" always refer to the code that is highlighted in red?

Now, I would like to create a Javascript object. The documentation says that Js objects have the 
type parameter Js.t. So I tried this:
```
  type foo = Js.t {. age: int, name: string };
  let data: foo = {
    pub age = 1;
    pub name = "sdf";
  } 
```
Which leaves me with this message:
```
  This is:
    {. age : int, name : string }
  But somewhere wanted:
    foo (defined as Js.t {. age : int, name : string })
```
I know that something in my code is missing but I have no clue how to actually create Js objects. Do I have to use something like bs.raw? Ideally, the error message would show a valid Js object literal (or whatever is needed). Also, the docs could say a bit more about this stuff.

**Comment by glennsl** [comment]
Good feedback! JS Objects can get a bit confusing since it's kind of shoe-horned into the language, and while Reason provides some sugar to make it smoother it looks a lot like, and is easy to confuse with other language concepts.

So what you really want is this:
```ml
  type foo = Js.t {. age: int, name: string };
  let data: foo = {
    "age": 1,
    "name": "sdf"
  }
```

The creation part is sugar for
```ml
[%bs.obj { age = 1; name = "sdf" }]
```

which is how you'd create a js object in plain OCaml.

**Comment by aloifolia** [comment]
Thank you very much! So, after all, this is mentioned in the [docs](https://reasonml.github.io/guide/javascript/converting/) (not very prominently though).

OK, I found another puzzling compiler message (not sure whether a separate issue would be appropriate). The version that does not work:
`let app () => <View><Text value="" /></View>;`
Error message:
```
File "[PATH]/app.re", line 11, characters 20-22:
Error: 18: <UNKNOWN SYNTAX ERROR>
```
After  I added spaces between the tags:
```
let app () => <View><Text value="" /></View>;
```

the message disappeared. So the parser somehow gets confused with `><` and so does the absolute beginner that is me ;-).

**Comment by glennsl** [comment]
Yeah, this is a known issue. See:
https://github.com/facebook/reason/issues/1374
https://github.com/facebook/reason/issues/1073

**Comment by aloifolia** [comment]
And another one... The following code generates an error message that was almost useless to me until I found a working example which showed me what was missing:

```
type sectionItem 'a = {
  key: string,
  value: 'a
};
let fl =
  <FlatList
    renderItem=(FlatList.renderItem (fun {item} => <Text value=item.key />))
    data=[|{key: "1", value: "abc"}|]
  />;
```
=> error message:
```
  This is:
    keyExtractor::(sectionItem string => int => string) =>
    ReasonReact.component ReasonReact.stateless ReasonReact.noRetainedProps
  But somewhere wanted:
    ReasonReact.component 'a 'b (defined as
      ReasonReact.componentSpec 'a 'a 'b 'b)
```
I had to add the `keyExtractor` property:
```
let fl =
  <FlatList
    renderItem=(FlatList.renderItem (fun {item} => <Text value=item.key />))
    keyExtractor=(fun item _ => item.key)
    data=[|{key: "1", value: "abc"}|]
  />;
```
After I've spent a few minutes on thinking about the compiler message, this is my interpretation of message: `<FlatList ...>` is a function application which is fed named parameters. If I miss any of the required parameters, Currying causes the generation of another function which still lacks bindings for these parameters - in this case it was `keyExtractor`.  I think it would be nice for noobs like me if the compiler could somehow show this to the user (maybe by making use of JSX syntax).

**Comment by glennsl** [comment]
This is a great candidate for improvement! I suggest creating a separate issue for it though.
