### ISSUE TITLE
Explicit error for `Js.Internal.fn`

### ISSUE THREAD

**Issue by chenglou** [reasonml-community/error-message-improvement#17]
```reason
external createClass : (Js.t 'classSpec => 'b) [@bs]= "createClass" [@@bs.val] [@@bs.module "React"];

let asd = createClass {"a":1} 2;
```

Add a message like "this indicates that you forgot to add [@bs] to the js function", if that's the case.

Also detect how many arguments there are

Also, reverse problem, when `[@bs]` is used at application side:

```reason
external foo : 'a => 'b = "createClass" [@@bs.val];

foo 1 2 [@bs];
```

**Comment by bobzhang** [comment]
Note I did it for vanilla oCaml https://github.com/bucklescript/bucklescript/blob/master/vendor/ocaml/typing/oprint.ml#L192
