### ISSUE TITLE
The type variable 'a occurs inside list 'a

### ISSUE THREAD

**Issue by rickyvetter** [reasonml-community/error-message-improvement#19]
This error is particularly confusing. I don't have a great idea for replacement, but maybe mentioning that this is a recursive type which will change/ grow over time. `list 'a` => `list list 'a` => `list list list 'a` etc.

repro:
```reason
[1,2,3] |> List.fold_left (fun a b => [a, b]) [];
```

error:
```
Error: This expression has type list 'a
       but an expression was expected of type 'a
       The type variable 'a occurs inside list 'a
```

super error:
```
   8 │
   9 │
  10 │ [1,2,3] |> List.fold_left (fun a b => [a, b]) [];
  11 │
  12 │

  This is:
    list 'a
  But somewhere wanted:
    'a
  The type variable 'a occurs inside list 'a
```

**Comment by chenglou** [comment]
Is that message generalizable? It's not true it's just for these recursive wrapping errors right? cc @cristianoc

**Comment by cristianoc** [comment]
This happens I guess when unifying 'a with list 'a, which does not have any finite solution.
I think the same would apply with any type constructor with a type argument.

**Comment by cristianoc** [comment]
Small repro:
```
type t 'a;

let inj (x: 'a) : t 'a => Obj.magic x;   

let f x => true ? x : inj x;
```
