### ISSUE TITLE
Better errors for ReasonReact gotchas

### ISSUE THREAD

**Issue by cristianoc** [reasonml-community/error-message-improvement#2]
Some of the gotchas are mentioned here:
  https://reasonml.github.io/reason-react/#reason-react-common-type-errors

Initial work to recognize those errors and provide more explanation:
  https://github.com/cristianoc/bucklescript/commit/2789c5b5e269629f016553c6730814e2131f5740

**Comment by chenglou** [comment]
We should also put the advice "**Note**: place `make` and `component` right beside each other! This helps readability and avoiding a corner-case type error for `state`." or something like that

**Comment by chenglou** [comment]
Closed in favor of #5 #6 #8
