### ISSUE TITLE
Explicit error for Js.internal.meth

### ISSUE THREAD

**Issue by glennsl** [reasonml-community/error-message-improvement#20]
```ml
type stream 'a = Js.t {.
  observe: ('a => unit) => unit
};
...
stream#observe Js.log;
```

Will give the error message
```
This is:
    (string => unit) => unit
  But somewhere wanted:
    Js.Internal.meth [ `Arity_1 'a ] 'b (defined as
      Js_internal.meth [ `Arity_1 'a ] 'b)
```

A better error message would be something along the line of "Dude, where's your [@bs.meth]?"

(This is somewhat related to #17 as well)

**Comment by ben-x9** [comment]
Yep, I just googled "But somewhere wanted: Js.Internal.meth", got to this page, read "Dude, where's your [@bs.meth]?" and immediately understood.
