### ISSUE TITLE
Comma separated arguments

### ISSUE THREAD

**Issue by baransu** [reasonml-community/error-message-improvement#21]
This is very basic error:
```
46 │       />
47 │       <button onClick=(reduce (fun _ => AddToDo))> (text "Add to do") </button>
48 │       (mapToElement (fun todo => <ul> (text todo) </ul>), state.todos)
49 │     </div>
50 │ };
 
This is:
  ('a, 'b)
But somewhere wanted:
  ReasonReact.reactElement
```
While typing fast I've accidentally wrote function arguments as in JavaScript, separated by comma.
Because I'm new to Reason I've send like 5 minutes figuring out what the actual error was.

It would be great if error message could have hints like in Elm explaining what the possible error is and how you can fix it.

**Comment by chenglou** [comment]
Fixed in the new syntax, thanks!
