### ISSUE TITLE
This kind of expression is not allowed as right-hand side of `let rec'

### ISSUE THREAD

**Issue by jackalcooper** [reasonml-community/error-message-improvement#25]
```
12 ┆ let init id name parent_id sub_domains = { id; name; parent_id ; sub_d
       omains }
  13 ┆ let rec decoder = let open! Json.Decoder in
  14 ┆   map4 (init)
  15 ┆     (field "id" int)
  16 ┆     (field "name" string)
  17 ┆     (field "parent_id" int)
  18 ┆     (field "sub_domains" (list decoder))
  19 ┆
  20 ┆ let rec view model (node:t) =

 This kind of expression is not allowed as right-hand side of `let rec'
```

I will be nice if more information is given.

**Comment by kennetpostigo** [comment]
@jackalcooper can you try putting a `;` at the end of decoder?

**Comment by jackalcooper** [comment]
@kennetpostigo syntax error is what I got

**Comment by kennetpostigo** [comment]
@jackalcooper can you post the whole piece of code?

**Comment by jackalcooper** [comment]
@kennetpostigo I've fixed it, no worries. It is because a decoder is not a function. Thanks for your replies.

**Comment by kennetpostigo** [comment]
ah, yea you didn't use the `=>` :)

**Comment by bassjacob** [comment]
Perhaps we can print the kind that is inferred?

**Comment by jackalcooper** [comment]
@bassjacob Yeah, I think it will be a good idea to print something like "xxx is a value. Try convert it to a  function to make it recursive."
