### ISSUE TITLE
Warning: This optional argument cannot be erased

### ISSUE THREAD

**Issue by glennsl** [reasonml-community/error-message-improvement#3]
https://ocaml.org/learn/tutorials/common_error_messages.html#Warning-This-optional-argument-cannot-be-erased

**Comment by chenglou** [comment]
How do you like the current one In super errors?

**Comment by glennsl** [comment]
So this is what I'm currently getting, and is hopefully the latest, but just in case I'll list it here:
```
 This is an optional argument at the final position of the function; omitting it while calling the function might be confused with currying. For example:

  let myTitle = displayTitle "hello!";

if `displayTitle` accepts an optional argument at the final position, it'd be unclear whether `myTitle` is a curried function or the final result.

Here's the language's rule: an optional argument is erased as soon as the 1st positional (i.e. neither labeled nor optional) argument defined after it is passed in.

To solve this, you'd conventionally add an extra () argument at the end of the function declaration.
```

First of all, I'd like it to be more structured. Right now it's a bit of a wall of text. I think the first sentence should explain the error concisely and be able to stand alone. The goal being to quickly identify the error once I've encountered it several times and thoroughly understand it. The following section could then elaborate on the cause of the error, and there could perhaps be a "Language rule" section that is very formal and precise following that. In any case, more structure, less wall of text.

Secondly, the code example references a function that is not defined anywhere, and has nothing to do with my code. It doesn't even resemble my code, because the error would occur in the function definition that's not included. (Producing a code example based on my code is of course a tall order, but I think the rust compiler is actually capable of doing that. One can always dream :D).

Thirdly, "... it'd be unclear whether `myTitle` is a curried function or the final result." is using incorrect terminology I think. It ought to be ".. it'd be unclear whether `myTitle` is partially or fully applied."

Fourthly (?), The error could also be solved by moving a non-optional argument to the end.

Also the highlighting seems wrong:
<img width="384" alt="screen shot 2017-08-23 at 10 48 30" src="https://user-images.githubusercontent.com/5207036/29638281-0a34feae-8857-11e7-9ff6-880cec0fefa7.png">
