### ISSUE TITLE
Warning "This expression should have type unit" could explain a little more

### ISSUE THREAD

**Issue by zploskey** [reasonml-community/error-message-improvement#33]
> This expression should have type unit

It would be nice if this additionally said "or the returned value is ignored".

An example of this causing confusion (thanks to @Sekib):
```reason
  didMount: fun _self => {
    Js.log "Component mounted";
    Bs_fetch.fetch "https://jsonplaceholder.typicode.com/posts";  /* WARNING */
    ReasonReact.NoUpdate
  },
```

**Comment by jaredly** [comment]
Maybe "this expression has a return value, but you're not doing anything with it. If this is on purpose, put a `|> ignore` at the end.

**Comment by SekibOmazic** [comment]
@jaredly definitely. I did exactly that in my sample project.
