### ISSUE TITLE
The type of this expression contains type variables that cannot be generalized - for retainedProps

### ISSUE THREAD

**Issue by jaredly** [reasonml-community/error-message-improvement#4]
if you make a retainedProps ReasonReact component but don't override `retainedProps` in the component record, you get this error

**Comment by cristianoc** [comment]
Thanks for the report.
This is handled in https://github.com/cristianoc/bucklescript/commit/2789c5b5e269629f016553c6730814e2131f5740, though it needs a cleanup pass for the wording of the error message.

<img width="679" alt="screen shot 2017-08-22 at 6 19 44 pm" src="https://user-images.githubusercontent.com/7965335/29576101-f1e7cdf4-8766-11e7-84d8-ee9bfa927c2b.png">

https://github.com/reasonml-community/error-message-improvement/issues/2

**Comment by chenglou** [comment]
Repro:

```reason
let component = ReasonReact.statelessComponentWithRetainedProps "asd";
let make _children => {
  ...component,
  render: fun _self => {
    <div/>
  }
};
```

**Comment by chenglou** [comment]
Repro for stateful:

```reason
let component = ReasonReact.statefulComponent "Test";
let make _ => {
  ...component,
  initialState: fun () => [],
  render: fun {state} => {
    let _ = state === [];
    ReasonReact.nullElement
  }
};
```
