### ISSUE TITLE
Uncurried application with wrong number of arguments gives type error about variant types.

### ISSUE THREAD

**Issue by cristianoc** [reasonml-community/error-message-improvement#47]
This snippet uses uncurried application with only 1 argument instead of 2:
```
let add = [@bs] ((x, y) => x + y);

let x = [@bs] add(5);

```
The error message is about variant types:
```
  This has type:
    ((int, int) => int) [@bs] (defined as ((int, int) => int) [@bs])
  But somewhere wanted:
    (('a) => 'b) [@bs] (defined as (('a) => 'b) [@bs])
  These two variant types have no intersection
```

**Comment by cristianoc** [comment]
If one omits the `[@bs]` annotation, a super-error kicks in:
https://github.com/BuckleScript/bucklescript/blob/master/jscomp/super_errors/super_typecore.ml#L154

Though in that case the internal representation is for `Tconstr`, while in this issue the error is about `Tvariant`. 
@bobzhang what's the internal representation likely to be in this case?

**Comment by bobzhang** [comment]
you can see the output via
```
jscomp>bsc -dsource -bs-syntax-only -bs-eval 'type t = a -> b [@bs]'
type t = ([ `Arity_1 of a ],b) Js.Internal.fn
```

Note I introduced `Arity_n` tag for better error message to avoid counting, maybe it is not needed any more

**Comment by cristianoc** [comment]
Fixed in https://github.com/BuckleScript/bucklescript/pull/2471.
