### ISSUE TITLE
JSX with no single root component yields consider adding ;

### ISSUE THREAD

**Issue by thangngoc89** [reasonml-community/error-message-improvement#50]
Simple code like this:

```reason
let component = ReasonReact.statelessComponent("Page");

let handleClick = (_event, _self) => Js.log("clicked!");

let make = (~message, _children) => {
  ...component,
  render: (self) =>
    <div onClick=(self.handle(handleClick))> (ReasonReact.stringToElement(message)) </div>
    <Button color="danger">
      (ReasonReact.stringToElement("Danger"))
    </Button>
};
```

Error:

```
Line 9:5-11 Syntax error, consider adding a `;' before
```

At least remove the `adding a ";"`. it's quite frustrating for beginner

**Comment by stereobooster** [comment]
Fix for the error: use root JSX element or use [React.Fragment](https://github.com/reasonml/reason-react/issues/162). Note for future googlers

**Comment by chenglou** [comment]
<img width="1178" alt="Screen Shot 2020-07-25 at 5 56 23 PM" src="https://user-images.githubusercontent.com/1909539/88468969-29d2ee00-cea0-11ea-97f8-fa39330152e6.png">

A bit more accurate under the new `res` syntax now
