### ISSUE TITLE
Option(string) shouldn't lead to "Unknown Syntax Error"

### ISSUE THREAD

**Issue by codekiln** [reasonml-community/error-message-improvement#53]
I was getting an error upon trying to use an option of a string:
![before](https://user-images.githubusercontent.com/140930/36629792-0c7a16fa-1929-11e8-8619-a5065da2bb48.png)
 
I [searched in reason community examples for option](https://github.com/reasonml-community/reason-react-example/search?utf8=%E2%9C%93&q=Option&type=), and got the sense that it was `option(string)`, which was correct:
![after](https://user-images.githubusercontent.com/140930/36629801-38b51eae-1929-11e8-9e57-8fca7937122c.png)

Suggested error message:
"Line 103: syntax error around **Option**(string); did you mean **[option](https://reasonml.github.io/docs/en/variant.html#option)**(string)?"

**Comment by chenglou** [comment]
A bit better under the new `.res` syntax now: <img width="1020" alt="Screen Shot 2020-07-25 at 5 58 11 PM" src="https://user-images.githubusercontent.com/1909539/88468992-69013f00-cea0-11ea-8f38-924482b9999d.png">
