### ISSUE TITLE
JSX: This call is missing an argument of type string

### ISSUE THREAD

**Issue by stereobooster** [reasonml-community/error-message-improvement#61]
```
  12 ┆ <p className={"pagination"}>
  13 ┆   <a href={j|/$storyType/$prev|j} className="navigate">
  14 ┆     textEl("← prev")
  15 ┆   </a>
  16 ┆   <span className={"pages"}>

  This call is missing an argument of type string
```

Actual error missing curly braces (`{}`) around `textEl` (`let textEl = ReasonReact.stringToElement;`)

```
<a href={j|/$storyType/$prev|j} className="navigate">
  {textEl("← prev")}
</a>
```

**Comment by jaredly** [comment]
btw @chenglou it would be cool if we could make the parser not need those enclosing braces for simple function calls like that

**Comment by stereobooster** [comment]
talking about syntax: is there a way to write this shorter?

```reason
<span>
  {ReasonReact.stringToElement({j|$comments_count comment$comments_plural|j})}
</span>
```

**Comment by jaredly** [comment]
I generally have `let str = ReasonReact.stringToElement` at the top of a file to cut down on that. I'd love to change the jsx ppx to auto-wrap string literals
