### ISSUE TITLE
Error: Syntax error

### ISSUE THREAD

**Issue by iddan** [reasonml-community/error-message-improvement#68]
Inserted:
```reason
type range('a) = {
    start: 'a,
    end: 'a
};
```
Expected: meaningful error that end is a keyword so it can't be used as a record field

**Comment by joprice** [comment]
Looks like this is fixed on master. I get the following error:

`Error: 521: end is a reserved keyword, it cannot be used as an identifier. Try `end_` or `_end` instead`

**Comment by iddan** [comment]
Let this be closed once published. I can see it still reoccurs in https://reasonml.github.io/en/try

**Comment by codekiln** [comment]
Is this fixed for all reserved keywords? Came here from https://reasonml.chat/t/is-there-a-list-of-reserved-words-for-reason-aka-reserved-keywords-identifiers/1213/2 .

**Comment by chenglou** [comment]
Fixed in the new `.res` syntax
