### ISSUE TITLE
Unhelpful error when forgetting semicolon on `switch` that is followed by a record expression

### ISSUE THREAD

**Issue by rigdern** [reasonml-community/error-message-improvement#77]
### Snippet

```reason
type data = {number: int};

let update = (state: option(int)): data => {
  let x =
    switch (state) {
    | None => 0
    | Some(value) => value
    }

  {number: x};
};
```

### Error

`Error: SyntaxError in block`

![image](https://user-images.githubusercontent.com/199935/51509407-d153f980-1dad-11e9-82d5-15d7e28d0b7b.png)

### Actual Mistake

The closing bracket of the `switch` needs a semicolon.

The error is unhelpful in that it highlights the entire `switch` expression. If you have a large `switch` expression like I did, then you'll be skimming through the whole thing trying to identify your syntax error.

### Repro Info

- Reason 3.3.7 @ 43efc14
- ocaml@4.7.1003@d41d8cd9
- Compiling with ocamlopt

**Comment by chenglou** [comment]
Fixed in the new `.res` syntax
